### ISSUE TITLE
Elements aren't dismissed (or are layered) in compose window modals

### ISSUE THREAD

**Issue by rubahness** [alicerunsonfedora/hyperspace#51]
Browser: Firefox 52.4.1

Steps: 
1. click Add Emoji on toot compose box
2. click outside Add Emoji pop up

Expected the pop up to disappear, but it remains visible.  Clicking "Set Visibility" at this point will result in the pop ups layering.  

Also happens with Add Warning popup, but since there's a "Save" button and the background is dimmed, the expected behavior could be argued either way.

**Comment by alicerunsonfedora** [comment]
I'll have to set up some tracking in the event handler to see if it clicks in the emoji picker or not to hide it, unless the `Callout` component in Fabric UI has that functionality ready.

As for the dialog overlap, this is probably because I didn't set them as blocking dialogs, meaning that the user cannot click away from the dialog. In the Fabric UI guidelines, Microsoft advises to not apply blocking to dialogs if the action being requested isn't pressing:

> Do not use a blocking Dialog unless absolutely necessary because they are very disruptive.

Given the nature of these dialogs, I might go against that guideline and turn them on to prevent the overlap.

**Comment by alicerunsonfedora** [comment]
Some of the dialog clutter will probably be reduced via dropdowns such as #58 .
