### ISSUE TITLE
Not show "via" of remote toots

### ISSUE THREAD

**Issue by cutls** [alicerunsonfedora/hyperspace#52]
Mastodon API couldn't get "via"(the app used to toot) from remote toots on Federated TL, Home TL and so on. However, this app show "determination (Web)." If the post was posted via Web, Mastodon API will return "Web," not empty.
This app should not show "via" if the toot's application info is empty.

**Comment by alicerunsonfedora** [comment]
Very true. I kept it at `determination (Web)` because it is assumed that one of the two things happened:
* The web client on that instance isn't registering
* The person posting the status hasn't turned on the setting that allows them to attach the application name

I'll need to look into this to see if people want this change to be applied or if the "determination" metaphor should continue to be used.

**Comment by cutls** [comment]
Yeah, the latest Mastodon can opt-out it at "Disclose application used to send toots (checkbox)." People may misunderstand that toots which are "determination(Web)" must be posted from Web. I think showing "unknown" is better than "determination(Web)."

**Comment by alicerunsonfedora** [comment]
I could probably re-word it so that it says via `determination (unknown)` instead. Luckily, you can hover over it and it'll display a warning saying that Hyperspace couldn't get the application name.

**Comment by cutls** [comment]
Thank you.
Perhaps because I could not understand English like a native, I might misunderstand this word.

**Comment by alicerunsonfedora** [comment]
No problem. 'Determination' is more of a thematic choice here than a practical one. It's part of why Hyperspace is called what it is and why I describe it as a "fluffy" client for Mastodon.

**Comment by BNolet** [comment]
I thought as well this was a misused word. Perhaps instead use the word "indeterminate".
