### ISSUE TITLE
Images are stretched in slideshows when they are wide but not tall

### ISSUE THREAD

**Issue by narFnarF** [alicerunsonfedora/hyperspace#71]
Images that are very wide but not very tall are stretched vertically in slideshows.

I noticed it in this post: https://pixelfed.social/p/narF/43117 (when you open it in Hyperspace)

**Comment by alicerunsonfedora** [comment]
This is most likely caused by the way the carousel draws the first item with `minHeight` and the CSS for the images in the carousel. I typically force them to at least 300px so that the carousel itself doesn't shrink to a size that is unusable until the slide is changed. 

I can try lowering the minHeight to see if this helps to ~25-100px.
